### ISSUE TITLE
[XSkull] - NullPointerException: Cannot invoke GameProfile.getProperties() because "profile" is null (Profileable::getProfileValue -> PlayerProfiles::getTextureProperty)

### ISSUE THREAD

**Issue by Sraconni** [CryptoMorin/XSeries#300]
**Description**
Some error occurs while configuration initializing.
Stack trace: https://pastebin.com/A7Q3rmbn

The **correctly** configuration file generated should look like this

```yaml
  info:
    title: '&a&lDetails &7#&f%(name)'
    items:
      back:
        material: REDSTONE_TORCH
        name: '&cBack'
      owner:
        material: PLAYER_HEAD
        name: '&7Residence owned by &f%(owner)'
        lore: 
        - '&7'
        - '&a ▶ Click &8|&f See all his residences'
      server:
        material: CREEPER_HEAD
        name: '&e&oServer Residence'
        lore: 
        - '&7'
      teleport-to:
        material: ENDER_EYE
        name: '&dTeleport to residence'
        lore:
        - '&7'
        - '&7Residence location:'
        - '&f%(world)&7@&f%(x)&7,&f%(y),&f%(z)'
        - ''
        - '&a ▶ Click &8|&f Teleport to residence.'
```

The **incorrect** configuration file **currently** generated

```yaml
info:
    title: '&a&lDetails &7#&f%(name)'
    items:
      back:
        material: REDSTONE_TORCH
        name: '&cBack'
      teleport-to:
        material: ENDER_EYE
        name: '&dTeleport to residence'
        lore:
        - '&7'
        - '&7Residence location:'
        - '&f%(world)&7@&f%(x)&7,&f%(y),&f%(z)'
        - ''
        - '&a ▶ Click &8|&f Teleport to residence.'
```

Code here
```java
//initItems
        if (ResidenceUtils.isServerLand(getData().getResidence())) {
            setItem(14, new GUIItem(CONFIG.ITEMS.SERVER.prepare().get(getViewer())));
        } else {
            setItem(14, new GUIItem(CONFIG.ITEMS.OWNER.prepare(getData().getOwner())
                    .setSkullOwner(getData().getResidence().getOwnerUUID())
                    .get(getViewer())) {
                @Override
                public void onClick(Player clicker, ClickType type) {
                    ResidenceListUI.open(getViewer(), getData().getOwner());
                    PluginConfig.GUI.CLICK_SOUND.playTo(getViewer());
                }
            });
        }

//ConfiguredItem
            ConfiguredItem OWNER = ConfiguredItem.create()
                    .defaultType(Material.PLAYER_HEAD)
                    .defaultName("&7Residence owned by &f%(owner)")
                    .defaultLore(
                            "&7",
                            "&a ▶ Click &8|&f See all his residences"
                    ).params("owner").build();

            ConfiguredItem SERVER = ConfiguredItem.create()
                    .defaultType(Material.CREEPER_HEAD)
                    .defaultName("&e&oServer Residence")
                    .defaultLore(
                            "&7"
                    ).build();
```

Full source code: https://github.com/ArtformGames/ResidenceList/blob/master/plugin/src/main/java/com/artformgames/plugin/residencelist/ui/ResidenceInfoUI.java#L105-L117

https://github.com/ArtformGames/ResidenceList/blob/master/plugin/src/main/java/com/artformgames/plugin/residencelist/ui/ResidenceInfoUI.java#L220-L233

**Version**
XSeries: 11.2.2
This error occurs with Paper-1.21 Build130
Tested on Paper-1.21.1 Build99 & Spigot-1.21.1 (CraftBukkit version 4324-Spigot-a759b62-d25e1e7), same error occurs.
