### ISSUE TITLE
[XItemStack] - Trim can't be added to leather armor

### ISSUE THREAD

**Issue by datatags** [CryptoMorin/XSeries#334]
**Description**
XItemStack won't serialize or deserialize trim on leather armor pieces, despite it being supported in vanilla. For example, deserializing the following results in regular leather armor:

```yaml
material: LEATHER_CHESTPLATE
trim:
    material: 'minecraft:diamond'
    pattern: 'minecraft:snout'
```

Intended result can be seen using this command: `/give @p minecraft:leather_chestplate[minecraft:trim={pattern:snout,material:diamond}]`

However, deserializing the following results in armor with visible trim:

```yaml
material: IRON_CHESTPLATE
trim:
    material: 'minecraft:diamond'
    pattern: 'minecraft:snout'
```

**Version**
This server is running Paper version 1.21.4-72-main@daddcf6 (2025-01-02T08:17:56Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
XSeries 13.1.0

**Additional Information**
In the deserialize method, this seems to be caused by the big if-elseif-else chain. Leather armor meta is checked [here](https://github.com/CryptoMorin/XSeries/blob/a9d001886d454f2290633c2149d53eb63e6c7f35/core/src/main/java/com/cryptomorin/xseries/XItemStack.java#L736), while the check for regular armor meta is below in an else block, [here](https://github.com/CryptoMorin/XSeries/blob/a9d001886d454f2290633c2149d53eb63e6c7f35/core/src/main/java/com/cryptomorin/xseries/XItemStack.java#L917-L928).
